# Generated by Django 5.2.1 on 2025-05-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pin_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
