# Generated by Django 5.2.1 on 2025-05-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_background_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
