# Generated by Django 5.2.1 on 2025-06-03 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanek_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sanektransaction',
            table='sanek_transaction',
        ),
    ]
